
sudo: false
language: node_js
node_js: 
  - "12.11.1"

 branches:
   only:
   - master

   cache:
   directories:
   -node_modules
  
   before_install:
   install:
   -npm install
   script:
   -npm test


    